import type { NextConfig } from 'next';

/**
 * Next.js configuration.
 * Optimized for static site generation and performance.
 */

// Determine if using custom domain (e.g., subscription-support.duckduckgo.com)
// Custom domains don't need basePath, GitHub Pages default URLs do
const useCustomDomain = process.env.CUSTOM_DOMAIN === 'true';

// Only use basePath for GitHub Pages default URL (username.github.io/repo-name)
// Custom domains are served at root and don't need a basePath
const basePath =
  process.env.NODE_ENV === 'production' && !useCustomDomain
    ? '/zendesk-subscription-support-messenger'
    : '';

const nextConfig: NextConfig = {
  // Enable React Compiler for automatic optimizations
  reactCompiler: true,

  // Static export for GitHub Pages deployment
  output: 'export',

  // Base path for GitHub Pages (repository subdirectory)
  // Empty when using custom domain, set to repo name for default GitHub Pages URL
  basePath,

  // Asset prefix must match basePath for static assets to load correctly
  assetPrefix: basePath,

  // Disable automatic image optimization for static export
  images: {
    unoptimized: true,
  },

  // Pages are statically generated by default in App Router. Server components
  // are used for build-time rendering, resulting in static HTML
};

export default nextConfig;
