import type { NextConfig } from 'next';
import { basePath } from './src/config/common';

/**
 * Next.js configuration.
 * Optimized for static site generation and performance.
 */

const nextConfig: NextConfig = {
  // Enable React Compiler for automatic optimizations
  reactCompiler: true,

  // Static export for GitHub Pages deployment
  output: 'export',

  // Base path for GitHub Pages (repository subdirectory)
  // Empty when using custom domain, set to repo name for default GitHub Pages URL
  basePath,

  // Asset prefix must match basePath for static assets to load correctly
  assetPrefix: basePath,

  // Disable automatic image optimization for static export
  images: {
    unoptimized: true,
  },

  // Allow cross-origin requests from Playwright test runner (127.0.0.1) and localhost
  // This is needed for development mode testing, including CI environments
  allowedDevOrigins: ['127.0.0.1', 'localhost'],

  // Pages are statically generated by default in App Router. Server components
  // are used for build-time rendering, resulting in static HTML
};

export default nextConfig;
