import type { NextConfig } from 'next';

/**
 * Next.js configuration.
 * Optimized for static site generation and performance.
 */
const nextConfig: NextConfig = {
  // Enable React Compiler for automatic optimizations
  reactCompiler: true,

  // Static export for GitHub Pages deployment
  output: 'export',

  // Base path for GitHub Pages (repository subdirectory)
  // Only applied during production build, not during development
  basePath:
    process.env.NODE_ENV === 'production'
      ? '/zendesk-subscription-support-messenger'
      : '',

  // Asset prefix must match basePath for static assets to load correctly
  assetPrefix:
    process.env.NODE_ENV === 'production'
      ? '/zendesk-subscription-support-messenger'
      : '',

  // Disable automatic image optimization for static export
  images: {
    unoptimized: true,
  },

  // Pages are statically generated by default in App Router
  // Server components are used for build-time rendering, resulting in static HTML
  // This provides optimal performance: pre-rendered pages served from CDN edge
  // No server computation needed per request, resulting in faster loads and lower costs
};

export default nextConfig;
