/**
 * Design tokens configuration and utilities.
 *
 * This file provides type-safe access to DuckDuckGo design tokens.
 * Design tokens are CSS custom properties generated by the design-tokens package.
 *
 * Usage:
 * ```tsx
 * import { DesignTokens } from '@/config/design-tokens';
 *
 * <div style={{ color: `var(${DesignTokens.color.primary})` }}>
 *   Content
 * </div>
 * ```
 *
 * Or in CSS:
 * ```css
 * .component {
 *   color: var(--spds-color-primary);
 * }
 * ```
 */

/**
 * Design token CSS variable names.
 * These correspond to tokens generated by the design-tokens package.
 *
 * Note: Actual token names may vary based on the package build output.
 * Check node_modules/design-tokens/build/static-pages/css/variables.css
 * for the actual generated variable names.
 */
export const DesignTokens = {
  /**
   * Color tokens
   * Use semantic color names for better maintainability
   */
  color: {
    /** Primary brand color */
    primary: '--spds-color-primary',
    /** Secondary brand color */
    secondary: '--spds-color-secondary',
    /** Page background color */
    pageBackground: '--spds-color-page-background',
    /** Main text color */
    text: '--spds-color-text',
    /** Disabled text color */
    disabledText: '--spds-color-disabled-text-color',
    /** Border color */
    border: '--spds-color-border',
  },
  /**
   * Spacing tokens
   * Use consistent spacing values throughout the app
   */
  spacing: {
    /** Extra small spacing */
    xs: '--spds-spacing-xs',
    /** Small spacing */
    sm: '--spds-spacing-sm',
    /** Medium spacing */
    md: '--spds-spacing-md',
    /** Large spacing */
    lg: '--spds-spacing-lg',
    /** Extra large spacing */
    xl: '--spds-spacing-xl',
  },
  /**
   * Typography tokens
   */
  typography: {
    /** Base font family */
    fontFamily: '--spds-font-family-base',
    /** Font sizes */
    fontSize: {
      sm: '--spds-font-size-sm',
      md: '--spds-font-size-md',
      lg: '--spds-font-size-lg',
    },
    /** Font weights */
    fontWeight: {
      normal: '--spds-font-weight-normal',
      medium: '--spds-font-weight-medium',
      bold: '--spds-font-weight-bold',
    },
  },
  /**
   * Border radius tokens
   */
  radius: {
    sm: '--spds-radius-sm',
    md: '--spds-radius-md',
    lg: '--spds-radius-lg',
  },
} as const;

/**
 * Gets a design token value at runtime.
 * Useful for programmatic access to CSS variable values.
 *
 * @param tokenKey - The CSS variable name (e.g., '--spds-color-primary')
 * @returns The computed value of the CSS variable, or empty string if not found
 *
 * @example
 * ```tsx
 * const primaryColor = getDesignTokenValue(DesignTokens.color.primary);
 * ```
 */
export function getDesignTokenValue(tokenKey: string): string {
  if (typeof window === 'undefined') {
    return '';
  }

  try {
    return getComputedStyle(document.documentElement)
      .getPropertyValue(tokenKey)
      .trim();
  } catch {
    return '';
  }
}

/**
 * Type helper for design token keys.
 * Ensures type safety when accessing token names.
 */
export type DesignTokenKey =
  (typeof DesignTokens)[keyof typeof DesignTokens][string];
